### ISSUE TITLE
The values of some constants are incorrectly defined, for arm-based linux platform

### ISSUE THREAD

**Issue by imlk0** [XuShaohua/nc#16]
It seems that the kernel uses a different value when defining constants for platforms such as `arm`.

For example, for the value of `O_NOFOLLOW`:
When compile for arm target, `0100000` is used:
https://elixir.bootlin.com/linux/latest/source/arch/arm/include/uapi/asm/fcntl.h#L6
```c
#define O_NOFOLLOW	0100000
```
However for some "generic" architectures, `O_NOFOLLOW` is defined as `00400000`.
https://elixir.bootlin.com/linux/latest/source/include/uapi/asm-generic/fcntl.h#L56
```c
#ifndef O_NOFOLLOW
#define O_NOFOLLOW	00400000	/* don't follow links */
#endif
```

`nc` does not appear to be dealing with such a situation at this time.

https://github.com/XuShaohua/nc/blob/767c815aef363c35670a993ccad2830fda5c9b44/src/platform/linux-types/fcntl.rs#L31

**Comment by XuShaohua** [comment]
Yes, that's an error, and there are more. Arch specific headers are not handled properly currently.
 Maybe I can fix these issues this week.

Thx.

**Comment by XuShaohua** [comment]
Hi, arm specific headers has been migrated today. New code can be accessed in v0.7.5.

Other arches will be handled when I'm free.

**Comment by imlk0** [comment]
> Hi, arm specific headers has been migrated today. New code can be accessed in v0.7.5.
> 
> Other arches will be handled when I'm free.

Thank you.
