### ISSUE TITLE
llvm_asm has been removed

### ISSUE THREAD

**Issue by bergwolf** [XuShaohua/nc#18]
`llvm_asm` has been removed in https://github.com/rust-lang/rust/pull/92816 and the crate no longer compiles with the latest nightly.

**Comment by XuShaohua** [comment]
It was replaced. Thx.

**Comment by XuShaohua** [comment]
Unlike llvm_asm!, asm! is only available on x86 and arm platforms (and risc-v), so the C shim code is used on other architectures in rust nightly.
