### ISSUE TITLE
APIs should be marked as unsafe

### ISSUE THREAD

**Issue by mmstick** [XuShaohua/nc#19]
Virtually none of these APIs are safe to call. It is possible to trigger segfaults with many of them if they're used incorrectly.

**Comment by XuShaohua** [comment]
Well, yes, some of the syscalls are unsafe to call directly, like mmap()/munmap(), which access raw pointers without guarantee.

**Comment by XuShaohua** [comment]
This issue will be closed if no more questions about unsafe interface
