### ISSUE TITLE
doc usage out of date

### ISSUE THREAD

**Issue by famz** [XuShaohua/nc#21]
Here:

https://docs.rs/nc/latest/nc/index.html

It still says

```
[dependencies]
nc = "0.7"
```

while the latest release is 0.8.

**Comment by famz** [comment]
I thought about sending a PR to update the version string but maybe it's better to have some way of avoiding manual updating for each version bump.

I'm not familiar with rust doc so cannot propose anything.

**Comment by XuShaohua** [comment]
Version value in README is modified by hand right now, and I don't find a good way to do this automatically.
