### ISSUE TITLE
fstatfs64 missing and examples look wrong

### ISSUE THREAD

**Issue by pwaller** [XuShaohua/nc#24]
I note that the *statfs64 functions are missing for some architectures, and the docs look wrong referring to 'stat63', and st_mode, which would relate to a stat not a statfs.

**Comment by XuShaohua** [comment]
statfs64() is unavaiable in, like aarch64, mips64 and x86_64. See statfs() instead.

**Comment by XuShaohua** [comment]
And the final question, about stat.st_mode, please provide the specific source file which might be wrong.
I've checked functions in calls/* relative to st_mode, all the them are being used in file stat syscalls.

**Comment by pwaller** [comment]
> And the final question, about stat.st_mode, please provide the specific source file which might be wrong.
> I've checked functions in calls/* relative to st_mode, all the them are being used in file stat syscalls.

You're right, I should have provided a reference at the time -- I think I misread '*fs*tat' as 'stat*fs*' at some point.

Thanks!
