### ISSUE TITLE
Accept is missing file descriptor return

### ISSUE THREAD

**Issue by pwaller** [XuShaohua/nc#25]
For example, on x86_64:

https://github.com/XuShaohua/nc/blob/00ab8d9fc38da479379dbbec64ffdb6bdfdf70ad/src/platform/linux-x86_64/call.rs#L22-L26

From the manpage:

> RETURN VALUE
>       Upon successful completion, accept() shall return the non-negative file descriptor of the accepted socket. Otherwise, -1 shall be returned, errno shall be set to  indicate the error, and any object pointed to by address_len shall remain unchanged.

**Comment by XuShaohua** [comment]
Yes, that's really a bug! accept() returns socket fd.
