### ISSUE TITLE
Calling a syscall with a NULL argument

### ISSUE THREAD

**Issue by perronet** [XuShaohua/nc#3]
Hi, I'm trying to use one of the syscalls but I'm having trouble because of the type of the arguments.
```
pub fn get_resource_hard_limit(pid: Pid) -> usize {
    let mut old_limit: nc::rlimit_t = default_rlimit_t();
    let new_limit: nc::rlimit_t = default_rlimit_t();
    match nc::prlimit64(pid as nc::pid_t, nc::RLIMIT_RTTIME, &new_limit, &mut old_limit) {
        Ok(_) => { println!("ok") },
        Err(_) => { println!("err") },
    }
    return old_limit.rlim_max;
}
```
The signature for this syscall is:
```
prlimit64(
    pid: pid_t,
    resource: i32,
    new_limit: &rlimit_t,
    old_limit: &mut rlimit_t,
)
```
This syscall can both set and get resource limits of a process, depending on which argument is a NULL. Here, to get the limits `&new_limit` would need to be NULL, but because these calls don't accept raw pointers I have no idea how to pass a NULL pointer as argument. Is there a workaround for this?

**Comment by XuShaohua** [comment]
Please help test this patch.

**Comment by perronet** [comment]
So far so good, I haven't spotted any issue.

**Comment by XuShaohua** [comment]
Ok, thx
